### ISSUE TITLE
Make alertify blocking like original prompt

### ISSUE THREAD

**Issue by justin-hackin** [alertifyjs/alertify.js#15]
Currently I'm trying to replace a prompt call with your beautiful little app here but I can't because I'm using it in a recursive function call.  In particular, if a particular name property is invalid, then the dialog will ask for a unique name through the prompt until it gets one.   It would be much nicer if the alertify.prompt just returned the value of the input.  It could be made to work as such if there is no callback function so we would have the best of both worlds.

**Comment by tellnes** [comment]
Please try to keep this library small and don't introduce large deps like a promise shim. Also, promises is just a fancy way of writing callbacks by my opinion. You still need a callback, just defined in another way. 

Lets wait for async/yield which is coming in es7. That will solve this issue.

**Comment by bradberger** [comment]
@tellnes I like your thought. While I can't quite agree with that regarding promises, the underlying thought of keeping the library small is right on point. 

The only issue right now is IE, and perhaps older Android, as [they've already landed everywhere else](http://caniuse.com/#search=promise). Having said that, I also think it makes sense for it to land *everywhere* to make use of it.

There is a 0.5 branch that's in the works, and that might be a better place for these kind of changes.

**Comment by tellnes** [comment]
What about adding a promise aware api. If a global `Promise` constructor is available, then it will return a promise, if not the api returns `undefined`. The old callback api should always be supported.

**Comment by bradberger** [comment]
Makes sense. Don't see any disadvantages to doing it that way. It should be quite lightweight to implement that way. I'll create a new issues for that, and add it to the "to-do" list.

**Comment by bradberger** [comment]
Created #32 to implement this. All PR's are welcomed!
