### ISSUE TITLE
Alertify.log prevents touch in Android 4.04 

### ISSUE THREAD

**Issue by ronaldjeremy** [alertifyjs/alertify.js#16]
We started getting complaints that our web app sometimes became unusable, and I was able to isolate it to Alertify.log on Android 4.04.  

It appears as if each alert will fill up an invisible space at the bottom of the screen and render it "un-touchable".  After sucessive alerts, the "untouchable" space grows until nothing at all can be touched on the screen.

I tested it on a device that was using Android 4.4.4, and it was fine.  Only the Android 4.04 device had the problem.

Below is a test scenario that i used and was able to reproduce the issue every time in Android 4.04.  Tap the button several times and eventually you can no longer tap it anymore until you refresh the page:
```
<!DOCTYPE html>
<html>
   <head>
      <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui"/>
      <link href="alertify.css" rel="stylesheet"/>
   </head>
   <body>
      <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
      <button onclick="alertify.log('test');">clickme</button>
      <script src="alertify.js"></script>
   </body>
</html>
```

**Comment by bradberger** [comment]
Merged fix from the gist into v0.3.15, so marking this closed.
