### ISSUE TITLE
Enter key opens&closes prompt dialog immediately

### ISSUE THREAD

**Issue by czirkoszoltan** [alertifyjs/alertify.js#17]
When an alertify prompt dialog is opened by pressing an Enter on a button, the Enter keyup will be received by alertify, and it will close the prompt dialog immediately (with success).
This can be reproduced on the homepage http://alertifyjs.org/ as well. Go to "Default dialogs" in the example section. There is the "Prompt dialog" button. Select it so it is active (maybe by clicking it with the mouse and then closing the dialog). When the "Prompt dialog" button is active, press enter. The dialog will be opened and closed immediately, and the notification will show "You've clicked ok". The problem is with the keyup signal on document.body. If one presses enter and keeps it pressed(!), the dialog will appear, and it won't be closed.

My workaround is, in the addListeners function:
var
                    seenKeydown = false,

...

                keydown = function (event) {
                    seenKeydown = true;
                };

...

                keyup = function (event) {
                    if (!seenKeydown) {
                        return;
                    }

...

                    self.unbind(document.body, "keydown", keydown);

...
                this.bind(document.body, "keydown", keydown);

...

So it ignores a keyup if it hasn't seen any keydowns. It is a hack, it should be done in a more clever way (maybe only the input field in the prompt dialog should intercept the ENTER keyup).

**Comment by bradberger** [comment]
Thanks for reporting it, and thanks for the clear explaination. I can reproduce it here, too. Seems like binding the keyup to the input field is a good way to go. I'm checking what it would take to make that happen.

**Comment by czirkoszoltan** [comment]
I think the keyup event must be bound to the document.body, at least to handle the Escape keypress. for confirm & alert dialogs, there is no input field, but Escape should work for those too. Maybe two separate keyup handlers are necessary, one on the input field for the Enter key, and the other one on document.body for the Escape key.

**Comment by bradberger** [comment]
Agreed. That makes sense. As mentioned, I'm looking it over now, but PR's are welcome, too :smile:

**Comment by bradberger** [comment]
Should be fixed. Let me know if you don't find that to be true.

**Comment by czirkoszoltan** [comment]
Thank you!
In the new branch (issue17), alertify.js lines 161-173:

                // common event handler (keyup, ok and cancel)
                common = function(event) {
                    self.hide();
                    global.addEventListener("keyup", key);
                    global.addEventListener("keydown", keydown);
                    global.removeEventListener("focus", reset);
                    if (hasOK) {
                        btnOK.removeEventListener("click", ok);
                    }
                    if (hasCancel) {
                        btnCancel.removeEventListener("click", cancel);
                    }
                };

those be removeEventListeners instead of addEventListeners for keyup and keydown

**Comment by bradberger** [comment]
Good catch! Just updated it now.
