### ISSUE TITLE
Include src folder in bower installation

### ISSUE THREAD

**Issue by tcsehv** [alertifyjs/alertify.js#18]
Right now only the minified version of the js and the compiled css are included in the bower package. When people want to customize the package or automate the integration (with gulp, Grunt etc.) of the package into their application it is easier to do from the source files.

solution: remove src from the ignore array in bower.json

**Comment by bradberger** [comment]
Agreed! Just updated it with commit 71229ce390 and v0.3.16 in bower. Thanks for the feedback!
