### ISSUE TITLE
alertify.confirm not closing when alert.success within

### ISSUE THREAD

**Issue by Donzella** [alertifyjs/alertify.js#20]
I have an alertify.confirm where upon OK there is an ajax call and upon success of that call there is an alertify.success. If the call happens quickly, the confirm doesn't close. I don't know for sure what is happening but that is the circumstances that I have and the result I am getting. If I comment out the success call in the code below, it closes fine. Here's the code:

```javascript
alertify.confirm("Are you sure you want to remove this?", function (e) {
				if (e) {
					// user clicked "ok"
					$.ajax({
						type: 'DELETE',
						url: '/Account/RemoveItem',
						data: JSON.stringify(j),
						contentType: "application/json; charset=utf-8",
						dataType: "json",
						success: function (data) {
							alertify.success("Item removed.");
						},
						error: function (e1, e2, e3) {
							alertify.error("There was an error removing that item. Sorry.");
						}
					});

				} else {
					// user clicked "cancel"
				}
			});
```

**Comment by bradberger** [comment]
Thanks for noting this! Will have a look at it, hopefully over the weekend.

To make sure I understand, it works if you comment out the success function that's part of the `$.ajax` call, or the `alertify.success` function call?

**Comment by Donzella** [comment]
The alertify.success call

Sent from my Windows Phone
________________________________
