### ISSUE TITLE
Possibility to "clear" all logs?

### ISSUE THREAD

**Issue by Clevero** [alertifyjs/alertify.js#21]
is there a way to clear all the logs?

In my case, when the user switched the theme, there will be a log (with a delay of 10s). And if the user then switch to an another theme, before the old log was deleted, there are two logs. But I want to have just one log. So delete the old and then spawn the new. Is this possible?

**Comment by bradberger** [comment]
Hey @Clevero that's a good question. I'm going to look into that and post what I find here. If it's not currently possible (I don't think it is, but need to double check), then it would be a great feature to have.

**Comment by bradberger** [comment]
Testing out an update now that would take care of the issue. It adds the option to set a max number of log items to be displayed at any given time, so you could use it as follows to accomplish what you need:

```javascript
alertify.set({ maxLogItems: 1 });
```

Right now, it's on a test branch, but if all goes well it will be published in `v0.3.19` shortly. Feel free to test it out now if you want and provide feedback. Thanks!

**Comment by bradberger** [comment]
This has been published to the new master/1.0 branch, so feel free to test it out and let me know what you think. It's worth noting that there are a few breaking changes in that branch, so just be aware of that when updating. Nothing major, but depending on your code some things from 0.3 might need to be updated slightly to work with 1.0
