### ISSUE TITLE
npm?

### ISSUE THREAD

**Issue by bizmurr** [alertifyjs/alertify.js#23]
Is this package available on npm?

**Comment by bradberger** [comment]
No, it's a bit of a naming issue, as other forks have already taken the name. @rufuscoder seems to have the original package from Fabien Dorion registered. Perhaps we can convince him to let us use that :smile:

**Comment by brabadu** [comment]
Since #26 is merged you can install it with npm by specifying scope

    npm install alertifyjs/alertify.js

**Comment by tellnes** [comment]
@brabadu Yes that works, but it is not a solution. Depending on git urls has some downsides. (Btw, scope means something else in npm (https://docs.npmjs.com/misc/scope))

Maybe it can temporarily be published under another name until the naming issues is resolved?

**Comment by bradberger** [comment]
Let's get a discussion going the naming issue now. Pavlos @ppoliani (who publishes the [alertify-js package](https://www.npmjs.com/package/alertify-js) and Rufus @rufuscoder who publishes the [alertify package](https://www.npmjs.com/package/alertify) would be up for consolidating those packages so we can reduce the confusion over package naming.

@tellnes In the meantime, any suggestions for a temporary package name?

**Comment by tellnes** [comment]
The `alertify` package has not been updated in three years and @rufuscoder does not respond here. I propose you try to email him with a CC to npm, Inc (https://docs.npmjs.com/misc/disputes).

Also, the `alertify.js` name is available.

**Comment by bradberger** [comment]
Ah, perfect. Thanks. Will do that now.

**Comment by ppoliani** [comment]
Hi guys,

I will remove the package from the `npm` and make a new pull request.

**Comment by bradberger** [comment]
@ppoliani Thanks so much Pavlos!

**Comment by tellnes** [comment]
I see you have published `alertify.js`. I think that is actually the best name on npm for the projects.

**Comment by bradberger** [comment]
@tellnes I agree. Actually I'm pretty new to npm publishing so I didn't realize that the `.` could be used in the package name. Thanks for pointing that out.

**Comment by tellnes** [comment]
I see that at bower the package is published without the dot. Maybe we should change that to remove confusion?

**Comment by bradberger** [comment]
Good point. How would that affect users who are already using the name as it is now? Does bower have a redirection for packages that move? (I can't seem to find anything on that...) I tried to publish it right now, but it gives a `DUPLICATE PACKAGE` error.

**Comment by bradberger** [comment]
Actually, the original Alertify package is still published there at `alertify.js`. It doesn't show up in the web search at bower.io, but it does via the command line.
