### ISSUE TITLE
Ember-cli / Broccoli fails to compile with Alertify.js

### ISSUE THREAD

**Issue by igorsantos07** [alertifyjs/alertify.js#25]
Adding `dist/js/alertify.js` to `Brocfile.js` causes an error, apparently related to sourcemap location: `ENOENT: no such file or directory, open '/development/brocfile-test/tmp/tree_merger-tmp_dest_dir-VTDuE1yJ.tmp/bower_components/alertifyjs/dist/js/src/js/alertify.js'`

To reproduce:

```shell
$ ember new alertify-test
$ cd alertify-test
$ bower install alertifyjs
$ vi Brocfile.js # add: app.import('bower_components/alertifyjs/dist/js/alertify.js');
$ ember s # then, open the page in a browser
```

Issue on `ember-cli`: [#3960](https://github.com/ember-cli/ember-cli/issues/3960)

**Comment by bradberger** [comment]
Looks like the path is wrong in the error message. It should be either `/bower_components/alertifyjs/dist/js/alertify.js` or `/bower_components/alertifyjs/dist/js/alertify.js`, not `bower_components/alertifyjs/dist/js/src/js/alertify.js`.

Honestly, I've never used Ember-cli / Broccoli, so I'm not really sure other than than, but figuring out why the error message is displaying the incorrect path would be a starting point.

**Comment by bradberger** [comment]
@igorsantos07 Closing for now, feel free to re-open if needed.
