### ISSUE TITLE
Unneccessary duplications / overrides - alertify-bootstrap-3.css

### ISSUE THREAD

**Issue by shaneparsons** [alertifyjs/alertify.js#28]
I haven't checked the **alertify-bootstrap.css**, but with **alertify-bootstrap-3.css** I've noticed a lot of unnecessary duplications / double instances of classes, some of which override previous instances of it.
e.g. 

```
line 86:
alertify-dialog {
   padding: 25px
}

line 153:
.alertify-dialog {
   padding: 0
}
```

```
line: 232
.alertify-button-cancel,
.alertify-button-cancel:active,
.alertify-button-cancel:focus,
.alertify-button-cancel:hover {
   color: #fff;
   background-color: #d9534f;
   border-color: #d43f3a
}

line: 241
.alertify-button-cancel:active,
.alertify-button-cancel:focus,
.alertify-button-cancel:hover {
   color: #fff;
   background-color: #d2322d;
   border-color: #ac2925
}
```

Interesting that there are **284** lines of code in this version compared to the **134** lines of code in the previous **alertify.bootstrap.css** from the master branch as well.

I'm doing some cleanup of it for my purposes atm, I'll post the code if you don't end up getting to it first.

Most of it seems like an easy fix.. just tedious.

**Comment by shaneparsons** [comment]
Just an update on this:

The **src** files seem fine, and make sense (basically cleaned up versions of the old files) it's just the **dist** files that are messed up.

This brings me to the conclusion that something funny is going on in the build process.

**Comment by shaneparsons** [comment]
Ah shit I see now.. **alertify-bootstrap-3.css** = **core.css** + **bootstrap.css**
Migrating over from the master branch is what caused the confusion, as there was no combined file.

**Comment by bradberger** [comment]
:smile: No worries. Maybe that should be documented someplace actually. Think some work actually could be done to improve the documentation. If you have any ideas, feel free to mention them. The whole [website itself is on GitHub](https://github.com/alertifyjs/website), too, for what it's worth.

**Comment by shaneparsons** [comment]
I think my main problem was that I didn't read the documentation or check the website, assuming everything was the same.

Putting a tiny readme / txt file with a bold name in the **dist/css** folder that states that it's only necessary to include one of the stylesheets could help people who are just migrating like I was.

Eventually in the future once most of the migration is done you could always just remove it too.

**Comment by bradberger** [comment]
Makes sense, good suggestion. Thanks!
