### ISSUE TITLE
Maintainers Wanted

### ISSUE THREAD

**Issue by bradberger** [alertifyjs/alertify.js#29]
Hey everyone, we're looking for some community assistance with maintaining the project going forward. Would like to hear from anyone interested in being a regular maintainer, managing and responding to issues, helping draft the future of the project, etc.

If you'd like to help out, please indicate such in the comments below, and we'll try to get you added to the @alertifyjs/contributors team so you can have read/write access to the repositories.

**Comment by bradberger** [comment]
The [Alertify.js Gitter.im chat room](https://gitter.im/alertifyjs/alertify.js) would be a great way to connect and discuss plans further.

**Comment by shaneparsons** [comment]
I'd love to become a "occasional" contributor to this repo if possible?

I say occasional only because I work 9-5 throughout the week, so anytime I put in would have to be evenings and weekends, which I can't guarantee every day.

But I'd definitely be willing to put in work every once in a while, if your looking for someone like that?

**Comment by bradberger** [comment]
@shaneparsons Definitely. That's kind of where we're all at with the project. Happily, sometimes I a project I'm working on uses Alertify so as to justify the time, but mostly it's a free-time project.

I've got to work up a little bit more documentation for contributing so as to get even more people on board, but more hands are definitely welcomed!

**Comment by shaneparsons** [comment]
Ah perfect! Is there anywhere you'd like me to start?

**Comment by bradberger** [comment]
Some of the issues you've brought up would be awesome if you had a chance to tackle them!

**Comment by bradberger** [comment]
For what it's wroth, also wanted to go on record for everyone involved that my vision (and that of Christian, too, I believe, based on previous conversations) is to keep the library as light as possible. There are definitely more feature rich options out there, but the goal here isn't really to match that. I don't want it to become something bloated, but something that's just very light weight and solves a small problem very well.

**Comment by bradberger** [comment]
Oh, and that basically we should avoid committing directly to master without discussing it first :smile: 

Also worth noting that the website is automatically built and deployed with passing builds on master, so any documentation changes should be done before pushing.

**Comment by bradberger** [comment]
For anyone who's on the team, just ping me to get Semaphore CI and Sauce Labs invites/credentials if you need them.

**Comment by ollie314** [comment]
If I can help to improve this, I'm on as an shiny and small contributor since my knowledge aren't so relevant in javascript..

**Comment by bradberger** [comment]
@ollie314 Awesome, thanks!

**Comment by expl0r3r** [comment]
I'd like to help too. I can help with ngAlertify.

**Comment by bradberger** [comment]
@expl0r3r Thanks!
