### ISSUE TITLE
jsDelivr repository

### ISSUE THREAD

**Issue by bradberger** [alertifyjs/alertify.js#30]
@jimaek Would it be possible to get the [alertify.js](http://www.jsdelivr.com/#!alertify.js) repository pointed here? Not sure how that all works, or even if it is possible, but the original repository [fabien-d/alertify.js](https://github.com/fabien-d/alertify.js) is no longer actively maintained, and this fork is.

**Comment by jimaek** [comment]
Sure you can simply send a PR to our repo and change the link. You can enable auto-updates as well if you wish. Use Github's web interface to speed things up.

**Comment by bradberger** [comment]
Thanks!
