### ISSUE TITLE
Max number of log messages ?

### ISSUE THREAD

**Issue by Eschwinm** [alertifyjs/alertify.js#34]
Planning on adding support to dismiss other log notifications when a new one is being shown ?
Because my whole screen will pop up with log messages at a given time.

It would be nice if theres going to be a setting which enables you to, lets say, 3 maximum log messages. If theres 3 on your screen and another one pops up, the top message will fade away.

Make this setting an integer from 0 to inifinite. 0 is unlimited messages.

Also in other plugin's I've seen a smooth transition when another log message pops up. All other visible messages will smoothly scroll up before the new one pops up!

**Comment by bradberger** [comment]
As mentioned via Gitter, I think this is a great idea and would definitely add overall value. Let's try to get this done asap.

**Comment by bradberger** [comment]
I'm a bit swamped with work right now, not sure if anyone would be available to create a PR for this?

**Comment by bradberger** [comment]
Created a new branch to test it out. The default is 3 per the suggestion.
It can be changed via the standard method for changing other options:

```javascript
alertify.set({ maxLogItems: 1 });
```

Let me know what you think. All tests are passing, so I think it can be merged pending any thoughts/comments/improvements.

**Comment by Eschwinm** [comment]
The max-logs work perfect, but I feel like when opening a dialog the very first time it's right away there, without a nice transition. I think this has been changed since this build unfortunately.

Also it would be very nice if you could click the overlay from the dialog to close the dialog. But very nice work you did there with the maxLogItems, works perfectly! :)

**Comment by bradberger** [comment]
Ah, okay. Good catch. Didn't notice the missing opening transition, will take a look at that.

**Comment by Eschwinm** [comment]
Could you notify me when you're releasing an update for this ? I'm looking forward to it, We're using this in the CMS we're currently building :)

**Comment by bradberger** [comment]
Yes, absolutely. It's actually complete, added a few more changes in the meantime so have to go through them all...

**Comment by Eschwinm** [comment]
When will you commit these new changes ? :')

**Comment by bradberger** [comment]
@Eschwinm Sorry, missed this message. Everything's been updated in the master/1.0 branch now, so that feature is there. If you need it backported `0.3` just let me know.
