### ISSUE TITLE
npm version outdated

### ISSUE THREAD

**Issue by mariusk** [alertifyjs/alertify.js#36]
Default version from npm is outdated (it's 0.3 something), and requiring/importing it does not seem to work.

**Comment by bradberger** [comment]
Okay, thanks for noting that. I've actually never used it with require(). Do you have a code sample I can use to test? The package itself should be updated now, `1.0.0-rc2` is the showing over on [NPM](https://www.npmjs.com/package/alertify.js)

**Comment by bradberger** [comment]
This should be taken care of, now I'm remembering to publish the npm updates right away. Had forgotten that npm isn't like bower to handle updates automatically based on git tags.
