### ISSUE TITLE
Dependency on jQuery unwanted

### ISSUE THREAD

**Issue by leolux** [alertifyjs/alertify.js#37]
This makes the component not lightweight but heavyweight. If possible try to get rid of this dependency.

**Comment by bradberger** [comment]
Actually, it doesn't depend on jQuery. jQuery is only a dev dependency which is used to make unit testing a bit easier. Alertify itself as it's used in the browser doesn't require jQuery.

**Comment by leolux** [comment]
Oh, I didn't see that it is only a dev dependency. Thanks for your answer.
