### ISSUE TITLE
Default styling looks nothing like examples

### ISSUE THREAD

**Issue by shaneparsons** [alertifyjs/alertify.js#39]
Title pretty much says it all.. The alerts look nothing like they do in the examples on alertifyjs.org.

Screenshot attached.

![screen shot 2015-09-22 at 10 26 02 am](https://cloud.githubusercontent.com/assets/5495493/10021140/7b1d8be8-6114-11e5-8355-8c9baf48d753.png)

Im pulling in alertify via npm btw.

**Comment by bradberger** [comment]
The screenshot seems to be from the 0.3 branch. If you're pulling from npm, are you sure you're `package.json` is set up to get the latest `1.0` release?

```json
{
    "devDependencies": {
          "alertify": "~1.0"
    }
}
```

**Comment by shaneparsons** [comment]
It works now that I manually put `1.0.0-rc3` in my package.json.
It should be noted that `npm install alertify.js --save` defaults to a `0.3` branch though.
My guess is the `-rc3` is throwing it off some how.
