### ISSUE TITLE
Default button values not populating

### ISSUE THREAD

**Issue by shaneparsons** [alertifyjs/alertify.js#40]
Without specifying `.okBtn("")` and  `.cancelBtn("")` values, the values seem to default to `UNDEFINED` rather than the default values of `ok` and `cancel`.

I had a quick look at the js to try to debug it, but couldn't figure out what's throwing it off.

![screen shot 2015-09-24 at 9 33 13 am](https://cloud.githubusercontent.com/assets/5495493/10074708/9243e326-629f-11e5-9ae1-1a00005e7743.png)

**Comment by bradberger** [comment]
Will check it out. Would it be possible to post an example to jsfiddle/jsbin/etc?

**Comment by shaneparsons** [comment]
I'll try to set that up for you when I get a chance

**Comment by bradberger** [comment]
Actually came across this today, so should have a fix shortly.

**Comment by bradberger** [comment]
Should be fixed in c6fcba2107344996bae72bdb529b785be7dccfe5, obviously let me know if you're still having issues.
