### ISSUE TITLE
Enhancement: Add transition to showing / hiding of dialogue

### ISSUE THREAD

**Issue by shaneparsons** [alertifyjs/alertify.js#41]
It'd be nice to have a subtle transition to diffuse the abruptness of the dialog appearing.
I'm thinking something along the lines of jquery's `fadeIn('fast')` / `fadeOut('fast')` would do wonders.

**Comment by bradberger** [comment]
Makes sense. There should have been one in there, but I'm not sure that maybe the issue isn't that it's just a bit too quick for it to be really noticeable.

Any thoughts on how long a transition you think would make sense? My thoughts are still to err on the "too quick" side of things to make it feel responsive, but suggestions are welcomed.

**Comment by bradberger** [comment]
Same goes for the timing of the transition, too, as perhaps updating that might help.

**Comment by shaneparsons** [comment]
I'm not sure what it's currently set to but `.25` with an `ease` is usually nice and snappy

**Comment by bradberger** [comment]
This got incorporated it c0dcab784e29501ab1c49c9e30cc41b124e96604. Turns out the process was a bit off, so the proper classes to trigger the transition weren't being added.
