### ISSUE TITLE
Enhancement: Set focus on show

### ISSUE THREAD

**Issue by shaneparsons** [alertifyjs/alertify.js#42]
For the `alertify.promt()` it'd be awesome if the input had focus when the dialog is shown!

**Comment by shaneparsons** [comment]
In addition to this, submitting the data by hitting the enter key would also be great!

That functionality could also apply nicely to the `confirm()` and `alert()` dialogs as well.. although the confirm dialogs might be better with the cancel button focused, or an option to turn off the focusing just in case "ok" is followed by a delete function.

**Comment by bradberger** [comment]
The focus for sure was in the older version, probably enter as well. It should be a relatively minor thing to add them back it, so I think that it would be a good addition.

@shaneparsons Are you in a position to do it? If you are, feel free to assign yourself to it.

**Comment by shaneparsons** [comment]
@bradberger Yeah definitely! How do I assign myself?

**Comment by bradberger** [comment]
@shaneparsons I think you'll have to accept the invite to join the contributors group first, and then you should have the option in the right column of the issue.

**Comment by ollie314** [comment]
Trying to adress the enhancement. Open to discuss since it's the first commit in this repo.

**Comment by shaneparsons** [comment]
It'd be awesome if there could be an option to set which button was focused with an option. i.e `.btnFocus('ok')` or `.btnFocus('cancel')`.. The default could remain `OK` but for destructive actions, the user would probably want `CANCEL` focused.

Should I open a new issue or just re-open this one?

**Comment by bradberger** [comment]
@shaneparsons Either one is fine.
