### ISSUE TITLE
bower: does not bring down ngAlertify.js?

### ISSUE THREAD

**Issue by ganySA** [alertifyjs/alertify.js#43]
Not sure why but when i install using bower i dont get the ngAlertify file...

**Comment by bradberger** [comment]
Thanks for reporting the issue, going to try to check it out today.

**Comment by bradberger** [comment]
What does the relative part of your `bower.json` config file look like? It might be that you're not getting the latest version which has that.

**Comment by bradberger** [comment]
Was able to try a fresh install via bower, and it's working now. But it was just updated to `1.0.1` so keep that in mind. The previous release candidate had an issue with the `ngAlertify` module anyways, so you'll definitely want to use this version. Any `0.x` version doesn't have the module.

**Comment by bradberger** [comment]
If you're still having issues with it, please feel free to comment and/or re-opoen

**Comment by ganySA** [comment]
Thanks will test!
