### ISSUE TITLE
alertify-bootstrap-3.css missing

### ISSUE THREAD

**Issue by shaneparsons** [alertifyjs/alertify.js#46]
I just updated to `1.0.2` and noticed that  `alertify-bootstrap-3.css` is missing.

**Comment by bradberger** [comment]
Yeah, I messed that up with the last commit. Deleted it when fooling around with some new changes. Do you think you could add them back? Worth noting that the CSS structure changed, and a lot of extra classes were removed, so the sass will need some tweaking from the previous versions. If you can't get to it I'll try over the course of the next few days.

**Comment by shaneparsons** [comment]
Sorry I've had no time for anything lately. I'll try to set aside time for this tonight!

**Comment by bradberger** [comment]
I know how that goes, no worries :smile:

**Comment by shaneparsons** [comment]
I just came to the realization that this is pretty much deprecated now that the `alertify.theme("bootstrap");` functionality is implemented.

No one needs extra stylesheets.

**Comment by bradberger** [comment]
Agreed, you're absolutely right, I think that method of theming will be much more flexible.
