### ISSUE TITLE
Allow customization of location of log elements

### ISSUE THREAD

**Issue by bradberger** [alertifyjs/alertify.js#49]
Add a new public method to allow customization of the position of log elements. Will need to also update the current CSS transitions to support various locations. There's already a request for positioning at top right, but my thought is that we should support any combination of top/bottom left/right for most compatibility.

**Comment by ollie314** [comment]
Is ready means you do the implementation ?

**Comment by bradberger** [comment]
No, if I'm ready to do it I'll self-assign it. Items which aren't assigned means that nobody is currently working on it. It's more that it's "ready" to be worked on by anyone. That label is from waffle.io which is kind of like Trello for GitHub - https://waffle.io/alertifyjs/alertify.js/join

**Comment by bradberger** [comment]
@mattiasnordqvist This just landed in the latest version.

**Comment by ollie314** [comment]
Awesome !
Too fast for me :) !
