### ISSUE TITLE
"Log with callback" and "Closing Log On Click" doesn't seem to work

### ISSUE THREAD

**Issue by tjratch** [alertifyjs/alertify.js#56]
Hi There,

Firstly, love what you have done.

It seems he "Log with callback' functionality is not working as intended. When clicking on the notification, the callback does not seem be called. I'm seeing this behaviour on your demo site as well.

**Comment by tjratch** [comment]
It seems "Closing Log On Click" also does not work

**Comment by tjratch** [comment]
After some digging, it appears to be related to the css.

**Comment by tjratch** [comment]
Bingo. Remove the "pointer-events: none" line in the following CSS block.

Change:
```
    .alertify-logs > * {
      max-height: 0;
      margin: 0;
      padding: 0;
      overflow: hidden;
      opacity: 0;
      pointer-events: none; }
```
to
```
    .alertify-logs > * {
      max-height: 0;
      margin: 0;
      padding: 0;
      overflow: hidden;
      opacity: 0;
 }
```

**Comment by tjratch** [comment]
Also, the cody in the dist folder does not match the code in the src folder. For instance, the code in the dist folder is missing the ```logPosition``` function

**Comment by tjratch** [comment]
Hope this Helps!

**Comment by bradberger** [comment]
@tjratch Thanks, yeah I'm not sure when it was broken, but you're right, that's the fix. Do you want to submit a PR or should I just go ahead and fix it?

**Comment by tjratch** [comment]
If it's not too much trouble, could you put the fix in?

**Comment by bradberger** [comment]
Sure, no problem. Not sure I'll get to it this evening, but should be able to do it tomorrow at worst.

**Comment by tjratch** [comment]
No rush. I made my change locally already
