### ISSUE TITLE
Closing prompt when hitting enter

### ISSUE THREAD

**Issue by stackoverflows** [alertifyjs/alertify.js#57]
Greetings,

It's accepted UI for prompt dialogs to be closed once the user entered in the required information and hit Enter. Unfortunately that doesn't happen here (at least on Chrome).

**Comment by bradberger** [comment]
You're right about that, that's definitely the desired behavior, so we'll add this to the list of items for the next release. For some reason I thought it was supposed to already do that, but maybe it was never set up, or maybe it's a bug.

@alertifyjs/contributors Anyone who has a chance to take it and work on it is welcomed to do so, if not I'll try during the course of the week to see what I can do.
