### ISSUE TITLE
dialog resizes when buttons are focused or unfocused

### ISSUE THREAD

**Issue by ericlenio** [alertifyjs/alertify.js#65]
When a button is focused, alertify draws a 1px border around that button. When unfocused, the border is removed. For some dialogs, like the first example dialog on alertifyjs.org, it shrinks/unshrinks the dialog by 2 pixels: open the example and then click anywhere but on the OK button and you will see the dialog shrink by 2 pixels. Here's a workaround that fixes it for me:

.alertify .dialog nav button:not(.btn):not(.pure-button):not(.md-button):not(.mdl-button){
  border:1px solid transparent;
}

**Comment by bradberger** [comment]
Thanks, good catch. That workaround is perfect. Will try to make sure it gets into the next release.

**Comment by bradberger** [comment]
Fixed in 371e545
