### ISSUE TITLE
Waiting for confirmation before continuing

### ISSUE THREAD

**Issue by RemizZ** [alertifyjs/alertify.js#66]
I just ran into a problem with the confirm prompt. I doesn't seem to stop the script to wait for a user input.
This is especially problematic because I have to use e.preventDefault() to even use it at all, which makes it quite difficult to use this script in a generic multi-purpose confirm function, because you can't just return to the default desired action after the user confirms or denies the confirm prompt.

Is there any easy solution to this? Thanks!

**Comment by bradberger** [comment]
I don't think there is a real solution to that. I understand that the native `confirm()` function does that, and I can definitely see where it would be useful to have that kind of option, but I think that technically it's just not possible to stop the script completely. I could be mistaken, but that's my current understanding of things.
