### ISSUE TITLE
how to change the position of the notification?

### ISSUE THREAD

**Issue by saritasa** [alertifyjs/alertify.js#71]
I'm using 1.6.1 installed via npm install
```
alertify.logPosition("top right");
alertify.success("saved");
```
console complains on first line, saying function doesn't exist.

**Comment by expl0r3r** [comment]
Did you `import` the module inside your js file?

**Comment by saritasa** [comment]
yes, I see the notification at the bottom right position. I Checked source
code and there is no method logPosition, but it exists inside current git
head. It means npm has older files for some reason

On Fri, Feb 19, 2016 at 1:44 PM, Kaushal <notifications@github.com> wrote:

> Did you import the module inside your js file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alertifyjs/alertify.js/issues/71#issuecomment-186421102>
> .
>



-- 
*Simplicity - Beauty of the Person. *
Clickbrand.com - making tomorrow today

**Comment by bradberger** [comment]
Are you sure you're using the same Alertify project? There are actually a few different ones on npm, and this one it currently at version [1.0.6](https://www.npmjs.com/package/alertify.js). 

I think you might be using [this Alertify package](https://www.npmjs.com/package/alertifyjs) currently, which is at v1.6. That's a different fork of the original project, and so has a bit different feature set.
