### ISSUE TITLE
Programmatically close or manipulate a dialog box

### ISSUE THREAD

**Issue by kfriend** [alertifyjs/alertify.js#72]
Is there an official way of doing this? I checked the docs, past issues for a related topic, and scanned the source for any exposed functionality, but wasn't able to find anything.

The situation I'm in is that I have an interface that auto saves a user's progress. When the user switches to a different area on the interface, the feature detects if the user's state is "dirty", and launches an alertify dialog, letting them know their change's haven't been saved yet. At the same time, the feature polls the user's state, and when it is clean, is supposed to either close the dialog box, or manipulate it to let the user know everything has been saved.

Thanks

**Comment by kfriend** [comment]
Also, I know you could query the DOM for the node, and manipulate it that way. I was looking for a less hacky way, if there was an official method of doing it.

**Comment by bradberger** [comment]
There isn't a better way. I believe this has been brought up before and it's something we'd like to do. I've added it to the list for the next minor release so we don't forget it.

**Comment by tnrich** [comment]
any movement on this one? Maybe the api could be something like: 
```js
var alertBox = alertify.error('I am an error')

function programaticallyHandleClose () {
 alertBox.close()
}

```

**Comment by PabloVallejo** [comment]
Any updates on this?

**Comment by PabloVallejo** [comment]
The dialog can be closed using:

``` js
$('.alertify').addClass('hide');
```
