### ISSUE TITLE
set alertify element location

### ISSUE THREAD

**Issue by andykais** [alertifyjs/alertify.js#76]
It would be helpful to be able to specify where alertify is located in the DOM. I for instance and using angular and if I want to put an `ng-click` attribute inside alertify, it needs to be within the ui-view to work properly
```
<div ui-view class="ng-scope"></div>
```

**Comment by bradberger** [comment]
Okay, I think we can do that. My idea would be a method something like this:

```javascript
alertify.parent(document.getElementById("my-element"));
```

and then the output would be appended as a child of whatever element is set as the parent, with `document.body` as the fallback if nothing was specified. Would that work?

**Comment by andykais** [comment]
Yes! That sounds perfect. Would this be part of the next release of alertify?

**Comment by bradberger** [comment]
@andykais Yes, it's now published with `1.0.10` and available via download here, bower, or npm.

**Comment by clark-stevenson** [comment]
:+1:

**Comment by andykais** [comment]
just tested 1.0.10 and the method does not appear to work, `alertify.parent(divElement)` returns undefined, meaning it has to be the last attribute in a chain and setting it with just 
```
alertify
  .log('test')
  .parent(document.getElementById('alertifyHolder'))
``` 
does not appear to change its location, and yes the element exists

**Comment by codeclown** [comment]
Chaining may not work (did not test), but setting it beforehand surely works.

```
alertify.parent(wrapper);
alertify.log('test');
```
