### ISSUE TITLE
Injecting text in an already visible Dialog

### ISSUE THREAD

**Issue by wingoku** [alertifyjs/alertify.js#84]
I am making a chat app. I want to inject the messages sent from other users in the Alertify Promt box which is already showing on the screen. How can I do that?

**Comment by ollie314** [comment]
Hi,
I think a thing like the following one should works,

```javascript
// Assume that you have only one alert open.
var yourText = "foo bar baz";
// ...
$(".alertify-logs .msg").html(yourText);
```
As long as your alert is visible, you'll can change the message inside.it.

**Comment by bradberger** [comment]
Closing this as it seems to have been answered. If not, feel free to comment and/or re-open. 

@ollie314 Thanks for the answer!
