### ISSUE TITLE
can i import alertify in react

### ISSUE THREAD

**Issue by Maopy** [alertifyjs/alertify.js#85]

**Comment by expl0r3r** [comment]
I suppose so.
We use webpack and this is what we do,
`import alertify from 'alertify.js';`

And use alertify as documented.

**Comment by DiganmeGiovanni** [comment]
I'm using this way:
`var alertify = require('alertify.js')`

And displaying alerts:
`alertify().alert('I am an alert')`

**Comment by bradberger** [comment]
Closing this as it seems to have been answered. If not, feel free to comment and/or re-open.
