### ISSUE TITLE
Port to TypeScript or include TypeScript Module

### ISSUE THREAD

**Issue by vladjerca** [alertifyjs/alertify.js#95]
I'm currently working on a new application using ng2.

I was thinking of porting the library to TypeScript, in order to offer support for ng2 and also have a JS output in order to easily support the ng-1 directives and native js support.

For the moment I've written a simple interface in order to export a module.

```ts
interface IAlertify {
    reset(): IAlertify;
    alert(message: string, onOkay?: Function, onCancel?: Function): IAlertify;
    confirm(message: string, onOkay?: Function, onCancel?: Function): IAlertify;
    prompt(message: string, onOkay?: Function, onCancel?: Function): IAlertify;
    log(message: string, click?: Function): IAlertify;
    theme(themeName: string): IAlertify;
    success(message: string, click?: Function): IAlertify;
    error(message: string, click?: Function): IAlertify;
    cancelBtn(label: string): IAlertify;
    okBtn(label: string): IAlertify;
    delay(time: Number): IAlertify;
    placeholder(str: string): IAlertify;
    defaultValue(str: string): IAlertify;
    maxLogItems(max: Number): IAlertify;
    closeLogOnClick(bool: Boolean): IAlertify;
    logPosition(position: string): IAlertify;
    setLogTemplate(template: string): IAlertify;
    clearLogs(): IAlertify;
    parent(prt: HTMLElement): IAlertify;
}

declare var alertify: IAlertify;

declare module "alertify" {    
    export default alertify;
}
```

If you guys are comfortable with a typescript port, I can create a pull request over the weekend, otherwise including the module in the current codebase to have it all when fetching the npm package, should suffice.

Let me know if I can offer any more details regarding this issue.
Thanks again for the great work.

**Comment by bradberger** [comment]
I love the idea of a TypeScript port. Actually have thought about rewriting it myself in the past, but never got around to it. So anything in TypeScript would be happily merged.

**Comment by bradberger** [comment]
@vladjerca It would defintely also be great to package it as an Angular 2 module. We have a super basic wrapper for Angular v1 right now, but I've yet to dig into the Angular 2 docs for what would need to be done to make it work. If you have any insights or want to help out with that any help would be most welcome. Thanks!

**Comment by vladjerca** [comment]
Well, I'll branch the repository this weekend and I'll start working on it. I'll submit a PR once it's ready to go.

**Comment by bradberger** [comment]
That's awesome, thanks!
