### ISSUE TITLE
Improve z-index for logs

### ISSUE THREAD

**Issue by jor3l** [alertifyjs/alertify.js#96]
This is a suggestion, use z-index: 1000 (currently 1) for logs. I had to fix this in order to get them working for my project and I think the alerts are supposed to go on top of everything :)

**Comment by bradberger** [comment]
Agreed! Closing this as it's actually a duplicate of #88 and it's definitely on the to-do list. If you can get to it before me, feel free to submit a PR.

**Comment by jor3l** [comment]
Sorry for the duplicate, Too Lazy; Didn't Read
